coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    changes: false
    project: false
    #project:
    #  target: auto
    #  if_no_uploads: error

    #patch: false
    patch:
      default:  # note this context
        target: "80%"

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default