coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    changes: false
    project: false
    #project:
    #  target: auto
    #  if_no_uploads: error

    patch: false
    #patch:
    #  target: "80%"
    #  if_no_uploads: error

comment:
  layout: "header, diff, changes, suggestions"
  behavior: default